name: LittleFly
version: '${project.version}'
main: fr.hillwalk.littlefly.LittleFly
api-version: '1.20'
softdepend: [PlaceholderAPI]
commands:
  fly:
    description: You can fly!
  tfly:
    description: You can temporaly fly!
  lfly:
    description: Commands for fly
